#locale: en_US
title: Learning curve
author: Dzmitry Laziuk
email: dm.laziuk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is about learning curve of mature programmer.
  He who tries to compete with newbies in constantly changing environment.
baseurl: "/"
url: "https://dmlaziuk.github.io"
github_username:  dmlaziuk
repository: "dmlaziuk/dmlaziuk.github.io"
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
#plugins:
#  - jekyll-feed

words_per_minute: 100

paginate: 8
paginate_path: /page:num/

author:
  name   : "Dzmitry Laziuk"
  avatar : "/images/avatar.png"
  bio    : "Mature programmer."
  email  : "dm.laziuk@gmail.com"
  uri    : "https://github.com/dmlaziuk"
  home   : "/about/"
  location : "Minsk, Belarus"
  facebook : "dzmitry.laziuk"
  linkedin : "dm-laziuk"
  github   : "dmlaziuk"

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
