title: Learning curve
author: Dzmitry Laziuk
email: dm.laziuk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is about learning curve of mature programmer.
  He who tries to compete with newbies in constantly changing environment.
baseurl: "/"
url: "https://dmlaziuk.github.io"
github_username:  dmlaziuk

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
